### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by space55** [containers/podman-py#101]
Hi,

I've been looking around a little bit for solid documentation for this project, as I plan to utilize it. I noticed there's no ReadTheDocs site, and `mkdocs` doesn't build anything except for a 404 page. I was curious if there is documentation hosted here, on GitHub Pages, on RTD, or others, or if there are plans do to so?

Thanks in advance!

**Comment by jwhonce** [comment]
@space55 It is on roadmap for this project. `make docs` will populate the build/html directory with documentation.

**Comment by aparcar** [comment]
Could you create a CI job to run that command? Documentation really comes in handy :)

**Comment by jwhonce** [comment]
@baude Is the ReadTheDocs refactor still in progress?

**Comment by umohnani8** [comment]
Docs are published now on readthedocs https://podman-py.readthedocs.io/en/latest/
