### ISSUE TITLE
upstream management of gating tests for distro consumption

### ISSUE THREAD

**Issue by lsm5** [containers/podman-py#111]
Fedora/RHEL etc. will need gating tests to be run along with the rpm updates. Something along the lines of `podman-tests` and `buildah-tests` subpackages that we already have. 

podman and buildah tests are in bats, while podman-py tests are in python. 

We need to decide on how to manage/maintain tests upstream so distros can easily consume them.

**Comment by lsm5** [comment]
I gotta check if gating tests can use something other than bats.

**Comment by lsm5** [comment]
> I gotta check if gating tests can use something other than bats.

https://docs.fedoraproject.org/ko/ci/gating/ .. doesn't specify any language requirement. I can try just creating a new subpackage and see how things go.

**Comment by jwhonce** [comment]
@lsm5 If bats is required, I recommend we encapsulate the existing tests in a bats wrapper. This would require the podman-python-tests rpm to require all the necessary python3 and podman-py testing packages.

**Comment by edsantiago** [comment]
BATS isn't required, at all. You just need something that conforms to the Fedora gating-test spec: a `gating.yaml` (easy) and a `tests/tests.yml` structure (hard).

**Comment by lsm5** [comment]
I'll check out some other python packages to get started with.

**Comment by umohnani8** [comment]
@lsm5 is this still an issue?

**Comment by lsm5** [comment]
> @lsm5 is this still an issue?

Closing for now. I'll revisit this later. Thanks
