### ISSUE TITLE
Cannot specify workdir when starting container

### ISSUE THREAD

**Issue by kevinwylder** [containers/podman-py#118]
Running podman version 2.2.1, with podman-py version 3.1.2.4 (the latest at the time of writing this)

When using the working dir kwarg [here](https://github.com/containers/podman-py/blob/main/podman/domain/containers_create.py#L206) it doesn't seem to have any effect on the container

After going in and changing `working_dir` to `work_dir` [here](https://github.com/containers/podman-py/blob/main/podman/domain/containers_create.py#L362) to match [the podman docs](https://docs.podman.io/en/latest/_static/api.html#operation/ContainerCreateLibpod) the flag started working. I think this is just a typo

**Comment by rhatdan** [comment]
Could you open a PR to fix this?

**Comment by kevinwylder** [comment]
I'd be happy to, but can't push a branch

```
08:42 ~/Code/Python/podman-py $ git push origin fix_container_run_workdir
ERROR: Permission to containers/podman-py.git denied to kevinwylder.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
08:43 ~/Code/Python/podman-py $ git remote -v
origin	git@github.com:containers/podman-py.git (fetch)
origin	git@github.com:containers/podman-py.git (push)
```

Here's the diff I was trying to push

```diff
diff --git a/podman/domain/containers_create.py b/podman/domain/containers_create.py
index 6841195..1c096fb 100644
--- a/podman/domain/containers_create.py
+++ b/podman/domain/containers_create.py
@@ -359,7 +359,7 @@ class CreateMixin:  # pylint: disable=too-few-public-methods
             "version": pop("version"),
             "volumes": list(),
             "volumes_from": pop("volumes_from"),
-            "working_dir": pop("working_dir"),
+            "work_dir": pop("working_dir"),
         }

         for item in args.pop("exposed_ports", list()):
```

**Comment by mwhahaha** [comment]
You need to push to your fork and then submit a pull request.  If the origin is not your fork it won't work

**Comment by kevinwylder** [comment]
That worked, I opened https://github.com/containers/podman-py/pull/119
