### ISSUE TITLE
create a pypi compatibility release to move users linking podman-py tothe new podman name

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [containers/podman-py#129]
a package of ours was using podman-py since back when it was the only name for the package, the recent name change got us a few packaging conflicts as well as a install overwrite/break situation (as the packages share the same import name)

first referenced in https://github.com/containers/podman-py/pull/100#issuecomment-915965227

**Comment by umohnani8** [comment]
Since this is over 2 years old, I don't believe it is still an issue so going to close.
Please re-open if it is still causing problems.
