### ISSUE TITLE
Context path error during image build

### ISSUE THREAD

**Issue by martin-endress** [containers/podman-py#152]
According to [image.build](https://github.com/containers/podman-py/blob/b4bbc98b7dd983f3dd44145314ab98c3e96c4b6e/podman/domain/images_build.py#L28), path references the build context directory. This works for ".", but not for subdirectories.

Given the following directory tree:
```
src
├── context_dir
│   ├── Dockerfile
│   └── <further files in context>
└── example.py
```
and the following code:
```python
client.images.build(
  path="context_dir/",
  dockerfile="context_dir/Dockerfile",
)
```
results in:
`Build Error( "stat /var/tmp/libpod_builder2054394681/build/context_dir/Dockerfile: no such file or directory`

Versions:
```
"Version": "3.4.2",
"ApiVersion": "1.40",
"MinAPIVersion": "1.24",
```

My Workaround:
```python
os.chdir('context_dir')
clientimages.build(
  path=".",
  dockerfile="Dockerfile",
)
```

**Comment by jonathanunderwood** [comment]
This is hopefully fixed by #155
