### ISSUE TITLE
Podman pods.list() returns truncated IDs that can not be used by pods.get()

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-py#153]
```
$ podman create pod --name mypod
$ cat podman-pods.py
import podman
client=podman.PodmanClient()
for i in client.pods.list():
    print(i)
    print(help(client.pods.get(pod_id=i)))
$ python podman-images.py
<Pod: 116291543d>
Traceback (most recent call last):
  File "/home/dwalsh/go/src/github.com/containers/common/podman-images.py", line 5, in <module>
    print(help(client.pods.get(pod_id=i)))
  File "/usr/lib/python3.10/site-packages/podman/domain/pods_manager.py", line 56, in get
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/podman/api/client.py", line 64, in raise_for_status
    raise not_found(cause, response=self._response, explanation=message)
podman.errors.exceptions.NotFound: 404 Client Error: Not Found (no pod with name or ID <Pod: 116291543d> found: no such pod)
```
I think there might be two bugs here.

1. List, should not truncate the IDs returned.
2. Podman pod.get() should be able to handle truncated IDs.

**Comment by rhatdan** [comment]
@mwhahaha @jwhonce PTAL

**Comment by rhatdan** [comment]
I took a quick look at the code, but do not really understand it.  The json call to the service seems to be bringing back the complete ID, not sure where it is getting truncated.

**Comment by rhatdan** [comment]
Ok, after examining this further, I understand a little better what is going on.

What I was trying to do was the equivalent of 
$ podman pod inspect mypod
But via Python. It seems that there are lots of additional calls required to do this?

**Comment by rhatdan** [comment]
Looks like the following gives me close to what I want.
```
import podman
client=podman.PodmanClient()
for i in client.pods.list():
    print(i.attrs)
```

**Comment by jwhonce** [comment]
@rhatdan, `get()` returns a pod object not a str. I could enhance the API calls to check if invoked with a str or an object.  `get(object)` currently is supported/implemented via `object.reload()`.

```python
with podman.PodmanClient() as client:
    pod = client.pods.get("mypod")
    print(pod.attrs)
```

https://github.com/containers/podman-py/blob/main/README.md shows iterating over images and containers using objects and `attr` dict's.

Closing this issue as "works as expected"
