### ISSUE TITLE
Inconsistent docstring format used throughout

### ISSUE THREAD

**Issue by jonathanunderwood** [containers/podman-py#156]
The docstring format used throughout the project is inconsistent. Sometimes they are reminiscent of Google docstrings, sometimes they look like numpy docstrings. A decision needs to be made and documented on the required docstring format to enable contributors to improve the docstrings.

**Comment by rhatdan** [comment]
@mwhahaha @jwhonce WDYT?

**Comment by mwhahaha** [comment]
I have no opinion so Google format would be fine.

**Comment by rhatdan** [comment]
@jonathanunderwood Can you open a PR to document this.

**Comment by umohnani8** [comment]
So I recently did a rework of the docs to be able to publish them to readthedocs and build without errors. The current documentation on readthedocs contain all the information a user would need for using the podman-py API and is clear. I don't think there is anything else to fix here given @jwhonce also added the clarification in the contributing.md.

Link to our readthedocs https://podman-py.readthedocs.io/en/latest/index.html.
