### ISSUE TITLE
example in the README cannot run

### ISSUE THREAD

**Issue by parmentelat** [containers/podman-py#17]
`README.md` shows an example that is broken

symbols like `system` and `images` must be either imported individually, or qualified as `podman.system`
plus, `ApiConnection` is mispelled as `APIConnection`

**Comment by rhatdan** [comment]
Is this issue still true?

**Comment by parmentelat** [comment]
I could not say as of now, but I did take care of that in #27 at first, so if/once it is rebased and merged this particular issue should vanish

**Comment by jwhonce** [comment]
See https://pypi.org/project/podman-py/, README.md updated to use new PodmanClient()
