### ISSUE TITLE
Stream option for pulling images

### ISSUE THREAD

**Issue by msisj** [containers/podman-py#171]
Hey,

Didn't know where to write it, because the change is needed between podman-py and podman REST Api, but as I'm not that familiar with podman REST Api source (honestly podman project is so complex I can't find definitions of the REST endpoints there :|) I decided to write here.

I'm wondering whether `stream` option could be a part of podman-py at some point.
In [docker-py there was such functionality](https://docker-py.readthedocs.io/en/stable/api.html) (stream (bool) – Stream the output as a generator. Make sure to consume the generator, otherwise pull might get cancelled.)
Thanks to it, it was possible to show progress of pulling images to the user, which is a cool and useful feature (note that regular `podman pull` does it by default).

The information about progress is actually somewhat there.
To prove that I've added one simple `print(body)` [here](https://github.com/containers/podman-py/blob/main/podman/domain/images_manager.py#L312).
Which showed such output : 
```
>>> import podman
>>> client = podman.PodmanClient(base_url='unix:///run/podman/podman.sock')
>>> image = client.images.pull(repository='ubi8', tag='latest')
{'stream': 'Trying to pull ubi8:latest...\n'}
{'stream': 'Getting image source signatures\n'}
{'stream': 'Copying blob sha256:3de00bb8554b2c35c89412d5336f1fa469afc7b0160045dd08758d92c8a6b064\n'}
{'stream': 'Copying blob sha256:3de00bb8554b2c35c89412d5336f1fa469afc7b0160045dd08758d92c8a6b064\n'}
{'stream': 'Copying blob sha256:c530010fb61c513e7f06fa29484418fabf62924fc80cc8183ab671a3ce461a8e\n'}
{'stream': 'Copying blob sha256:c530010fb61c513e7f06fa29484418fabf62924fc80cc8183ab671a3ce461a8e\n'}
{'stream': 'Copying config sha256:552ac8ae4291e2a8d5622cff4a7f978d3032664b3946831a5606bde9bdedef2a\n'}
{'stream': 'Writing manifest to image destination\n'}
{'stream': 'Storing signatures\n'}
{'images': ['552ac8ae4291e2a8d5622cff4a7f978d3032664b3946831a5606bde9bdedef2a'], 'id': '552ac8ae4291e2a8d5622cff4a7f978d3032664b3946831a5606bde9bdedef2a'}
```

Unfortunately all of this prints are showed **after** image is pulled as the `/images/pull` is a blocking method.
I've tried [similar method to logs](https://github.com/containers/podman-py/pull/162/files) with `stream=True` and `api.stream_frames` and even though it returned generator, the generator was filled **after** image was pulled.

My question is whether it is doable with current REST Api ?
Or are the changes on podman REST Api needed ?

**Comment by jwhonce** [comment]
@msisj tl;dr I think a adding the keyword `stream=True` and using `response.iter_lines()` _should_ work.

The go code for the podman API is a bit dense as we are supporting the compatible and libpod APIs. The RESTful endpoints are defined in `https://github.com/containers/podman/tree/main/pkg/api/server/register_*.go`, `r.Handle()` binds the path and method(s) to a go function, for example: `r.Handle(VersionedPath("/libpod/images/pull"), s.APIHandler(libpod.ImagesPull)).Methods(http.MethodPost)`

The image pull [API source]( https://github.com/containers/podman/blob/main/pkg/api/handlers/libpod/images_pull.go#L26) shows the service is always streaming the output as a concatenation of JSON objects, one per line. The service encodes and writes the JSON object as the libpod generates the output.

Adding `stream=True` to the [image pull `post()`](https://github.com/containers/podman-py/blob/main/podman/domain/images_manager.py#L308) with the existing `response.iter_lines()` which in turn calls 'response.iter_content()` _should_ provide the client with incremental updates. That is from reading the comments in the request library code...

`api.stream_frames` is not needed in this case as it supports a multiplexed stream (stdout and stderr) from the service which is not the output from `pull()`.
