### ISSUE TITLE
login is not implemented in SystemManager

### ISSUE THREAD

**Issue by awildturtok** [containers/podman-py#189]
Using podman-py 4.0.0

https://github.com/containers/podman-py/blob/f46011ca174215eee26321ee0aee22ab510e8ec5/podman/domain/system.py#L37

I don't know if this is intentional or not, but if it is intentional a comment or a `raise NotImplementedError()` would be useful to have.

**Comment by cdoern** [comment]
i'll work on implementing this as a way to get familiar with the code
