### ISSUE TITLE
Offer to help

### ISSUE THREAD

**Issue by nick-lehmann** [containers/podman-py#2]
Hi 👋 ,

I just read the announcement that podman is getting a new API that also offers compatibility with Docker. Even though it might seem creepy since this repository is only three days old, I would like to offer my help on this. Currently, I am employed as a python developer, have some spare time soon and would like to use podman from now on. Also, since I have implemented a tool that currently uses the python library for docker quite heavily, I am willing to put some time in the podman API.

However, I have a question about this repository. As I understood it, the podman API will have a docker compatible API. Why not start by forking the official docker libraries and modifying them? There was a lot of work invested in building them, they work quite well and have no real shortcoming as far as I can tell. Especially `docker-compose` is a lot more advanced currently than `podman-compose`.

**Comment by rhatdan** [comment]
Well the docker-py and docker-compose should just work with out compatability layer.  What we need is to return the advanced features of podman via the python library using the newer API.  If some of the code can be taken from docker-py and converted to the new API, then we are fine with this.

**Comment by rhatdan** [comment]
Also thanks @nick-lehmann for offering to help.

**Comment by rhatdan** [comment]
@baude @jwhonce WDYT?

**Comment by nick-lehmann** [comment]
@rhatdan thank you for the clarification. I would like to offer me to take a deeper look at how much of the docker library can be used and what can be reused. Also, a specification for the new API would be very helpful. Having just seen the announcement and skimmed through a few of the commits you guys have committed to `libpod`, the new API is still quite vague for me.

**Comment by jwhonce** [comment]
@nick-lehmann Below is a pointer to current API documentation.  It's a work in progress, please let us know what you find confusing or missing :-)  We are using swagger annotations on the go code to create this documentation. 

The main driver here is we're moving to a REST-like API, the endpoints that include /libpod/ have all the goodies from Podman included.  An example, would be pods.  

https://podman.readthedocs.io/en/latest/Reference.html

**Comment by nick-lehmann** [comment]
Thank you @jwhonce, this is certainly something I can work with. 

Is there anything I need to know? Anything that should be clarified before I dive into this a bit deeper? Is there anything that is important to you and that I should keep in mind?

As I already said, I would start by investigating `docker-py` and check what can be reused. Is it ok for you the interface that this package exposes will resemble this by `docker-py` a lot? This would be helpful for people like me who depend on `docker-py` and are familiar with it.

Otherwise, I still have three questions?
- Do you want this library to be asynchronous? The official `docker-py` is synchronous but there is an async alternative called [aiodocker](https://github.com/aio-libs/aiodocker) that could serve as a starting point.
- Where is the documentation coming from that you have posted? I have expected it to be in this repository but I do not see any.
- Are there any deadlines that you have set for this project?

**Comment by jwhonce** [comment]
@nick-lehmann 
 - I have a large PR coming that will make the code more "package-able' with current python tools
 - I'll have look at aiodocker and see if our backend can support that model
 - The documentation posted is generated from annotated go code. An example, https://github.com/containers/libpod/blob/master/pkg/api/server/register_info.go
- Release ASAP, it's software :-) Seriously, we would like to have something out in the next month.

**Comment by jwhonce** [comment]
@nick-lehmann I forgot one important detail and will update the readme RSN.  We are targeting python 3.6.  You may want to setup a virtual environment to ensure  you stay in that sandbox.

**Comment by nick-lehmann** [comment]
Ok, that's all I need for now 👍🏻 I will start by compiling the latest version of podman myself to have the current version of the new API and something to test with. Then I can check against `docker-py`.

**Comment by rhatdan** [comment]
Awesome, looking forward to the PRs
