### ISSUE TITLE
why the `__ALL__` definitions ?

### ISSUE THREAD

**Issue by parmentelat** [containers/podman-py#21]
just want to outline that

* `__ALL__` should be spelled `__all__`, like all other special names
* plus, and more to the point, there are lighter conventions to just rely on the *public*  / *_private* naming convention, which seems to be in place already since `_report_not_found` follows the *_private* pattern

So I just wanted to make sure that it was mandatory to have these defined for some higher level reason, like it's a redhat policy or something

Otherwise I'd suggest to simply drop it, as it serves no visible purpose (evidence of that being that it is currently misspelled), and just adds possibility for error

**Comment by jwhonce** [comment]
@parmentelat agreed, I appear to have been the one to create that issue.  I'll put together a PR to fix those.
