### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by parmentelat** [containers/podman-py#22]
I can see functions
* `system.get_info()` that uses libpod's path `/info`
* `system.show_disk_usage()` linked to `/system/df` 

should we not try to define some kind of mapping between all these names ?

**Comment by jwhonce** [comment]
@parmentelat To aid in developers moving from docker-py, our naming and parameters should be a superset of that API.

**Comment by rhatdan** [comment]
SGTM

**Comment by jwhonce** [comment]
The work for a compatible binding has begun and can be seen in the repository now.
