### ISSUE TITLE
Running new container fails to pull missing image

### ISSUE THREAD

**Issue by ewie** [containers/podman-py#231]
Try this Python script that runs a container from an image that has not been pulled yet:
```py
import podman

image = 'docker.io/library/alpine'

with podman.PodmanClient() as client:
    # client.images.pull(image)
    out = client.containers.run(image, ['echo', 'hello world'], remove=True)
    print(out)
```
It fails with:
```
Traceback (most recent call last):
  File "/home/ewie/test.py", line 7, in <module>
    out = client.containers.run(image, ['echo', 'hello world'], remove=True)
  File "/home/ewie/.venv/lib/python3.10/site-packages/podman/domain/containers_run.py", line 61, in run
    container = self.create(image=image, command=command, **kwargs)
  File "/home/ewie/.venv/lib/python3.10/site-packages/podman/domain/containers_create.py", line 274, in create
    response.raise_for_status(not_found=ImageNotFound)
  File "/home/ewie/.venv/lib/python3.10/site-packages/podman/api/client.py", line 63, in raise_for_status
    raise APIError(cause, response=self._response, explanation=message)
podman.errors.exceptions.APIError: 500 Server Error: Internal Server Error (docker.io/library/alpine: image not known)
```
Uncomment line 6 to manually pull the image and the container runs as expected:
```
b'hello world\n'
```
I see that images should be pulled automatically (like `podman run` on the command line) if the API responds with `404 Not Found`:
https://github.com/containers/podman-py/blob/2f8b45ab098eeda1c9c8bc9515b4650f38a83de4/podman/domain/containers_run.py#L62-L63
But the stack trace above shows that the API responds with `500 Server Error`.

About my system:
* podman-py: 2f8b45ab098eeda1c9c8bc9515b4650f38a83de4
* Python: 3.10.9
* Podman:
    ```
    Client:       Podman Engine
    Version:      4.4.0
    API Version:  4.4.0
    Go Version:   go1.20
    Git Commit:   3443f453e28169a88848f90a7ce3137fc4a4bebf-dirty
    Built:        Sat Feb  4 00:28:28 2023
    OS/Arch:      linux/amd64
    ```
* OS:
    ```
    Linux desktop 6.1.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 01 Feb 2023 17:07:39 +0000 x86_64 GNU/Linux
    ```

**Comment by chnrxn** [comment]
The traceback indicates that the API server returns a HTTP 500 instead of the expected 404 when an image is not found.

```
>>> c.containers.run('nginx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/podman/domain/containers_run.py", line 61, in run
    container = self.create(image=image, command=command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/podman/domain/containers_create.py", line 278, in create
    response.raise_for_status(not_found=ImageNotFound)
  File "/usr/local/lib/python3.9/site-packages/podman/api/client.py", line 63, in raise_for_status
    raise APIError(cause, response=self._response, explanation=message)
podman.errors.exceptions.APIError: 500 Server Error: Internal Server Error (nginx: image not known)
```

The run() method catches `ImageNotFound`, but `500 Server Error` will raise a generic `APIError`.

So is the client code expecting the wrong thing, or is the API server returning the wrong status?

**Comment by ewie** [comment]
The API service should return 404 (https://github.com/containers/podman/blob/38e6fab9664c6e59b66e73523b307a56130316ae/pkg/api/server/register_containers.go#L35-L36) and does so when I access it via curl:

    $ podman image rm --force --ignore docker.io/library/apline

    $ curl -v --json '{"image": "docker.io/library/alpine"}' --unix-socket /run/user/1000/podman/podman.sock http://localhost/containers/create
    * processing: http://localhost/containers/create
    *   Trying /run/user/1000/podman/podman.sock:0...
    * Connected to localhost (/run/user/1000/podman/podman.sock) port 80
    > POST /containers/create HTTP/1.1
    > Host: localhost
    > User-Agent: curl/8.2.1
    > Content-Type: application/json
    > Accept: application/json
    > Content-Length: 73
    >
    < HTTP/1.1 404 Not Found
    < Api-Version: 1.41
    < Content-Type: application/json
    < Libpod-Api-Version: 4.6.0
    < Server: Libpod/4.6.0 (linux)
    < X-Reference-Id: 0xc000014018
    < Date: Tue, 15 Aug 2023 19:31:36 GMT
    < Content-Length: 112
    <
    {"cause":"image not known","message":"no such image: docker.io/library/alpine: image not known","response":404}
    * Connection #0 to host localhost left intact

Creating the container via the API service with curl after pulling the image works as expected:

    $ podman pull docker.io/library/alpine
    Trying to pull docker.io/library/alpine:latest...
    Getting image source signatures
    Copying blob 7264a8db6415 done  
    Copying config 7e01a0d0a1 done  
    Writing manifest to image destination
    7e01a0d0a1dcd9e539f8e9bbd80106d59efbdf97293b3d38f5d7a34501526cdb

    $ curl -v --json '{"image": "docker.io/library/alpine"}' --unix-socket /run/user/1000/podman/podman.sock http://localhost/containers/create
    * processing: http://localhost/containers/create
    *   Trying /run/user/1000/podman/podman.sock:0...
    * Connected to localhost (/run/user/1000/podman/podman.sock) port 80
    > POST /containers/create HTTP/1.1
    > Host: localhost
    > User-Agent: curl/8.2.1
    > Content-Type: application/json
    > Accept: application/json
    > Content-Length: 73
    >
    < HTTP/1.1 201 Created
    < Api-Version: 1.41
    < Content-Type: application/json
    < Libpod-Api-Version: 4.6.0
    < Server: Libpod/4.6.0 (linux)
    < X-Reference-Id: 0xc0011822a0
    < Date: Tue, 15 Aug 2023 19:34:06 GMT
    < Content-Length: 88
    <
    {"Id":"24c97059c580ed420d8a18a40123770447410b03fe1679d6b5b8b73f25912e28","Warnings":[]}
    * Connection #0 to host localhost left intact

Tested with:

    Client:       Podman Engine
    Version:      4.6.0
    API Version:  4.6.0
    Go Version:   go1.20.6
    Git Commit:   38e6fab9664c6e59b66e73523b307a56130316ae-dirty
    Built:        Fri Jul 21 14:38:28 2023
    OS/Arch:      linux/amd64

podman-py ff636bcf7611178375cdaed8bc003482e2ac2bc2 on Python 3.11.3 still fails with the same APIError from status 500 as I've initially reported.

**Comment by rsommer** [comment]
As I am having the same problem, I tried nearly the same but I do get a HTTP 500 response from the API service:
```
─$ curl -v -H 'Content-Type: application/json' --data '{"image": "docker.io/library/elasticsearch:7.17.10"}' --unix-socket /var/run/user/1000/podman/podman.sock http://localhost/v4.6.0/libpod/containers/create
*   Trying /var/run/user/1000/podman/podman.sock:0...
* Connected to localhost (/run/user/1000/podman/podman.sock) port 80 (#0)
> POST /v4.6.0/libpod/containers/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 52
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.41
< Content-Type: application/json
< Libpod-Api-Version: 4.6.1
< Server: Libpod/4.6.1 (linux)
< X-Reference-Id: 0xc0005deb00
< Date: Tue, 22 Aug 2023 11:40:39 GMT
< Content-Length: 112
< 
{"cause":"image not known","message":"docker.io/library/elasticsearch:7.17.10: image not known","response":500}
* Connection #0 to host localhost left intact
```

This is on:
```
version:
  APIVersion: 4.6.1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.1
```

As far as the traces show, there is no attempt to fetch the image from a remote source, just local.

```
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="Looking up image \"docker.io/library/elasticsearch:7.17.10\" in local containers storage"
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="Normalized platform linux/amd64 to {amd64 linux  [] }"
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="Trying \"docker.io/library/elasticsearch:7.17.10\" ..."
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="reference \"[overlay@/home/ros/.local/share/containers/storage+/run/user/1000/containers]docker.io/library/elasticsearch:7.17.10\" does not resolve to an image ID"
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="Trying \"docker.io/library/elasticsearch:7.17.10\" ..."
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="reference \"[overlay@/home/ros/.local/share/containers/storage+/run/user/1000/containers]docker.io/library/elasticsearch:7.17.10\" does not resolve to an image ID"
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="Trying \"docker.io/library/elasticsearch:7.17.10\" ..."
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=info msg="Request Failed(Internal Server Error): docker.io/library/elasticsearch:7.17.10: image not known"
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=trace msg="{\"cause\":\"image not known\",\"message\":\"docker.io/library/elasticsearch:7.17.10: image not known\",\"response\":500}\n" API=response X-Reference-Id=0xc0005deb00
Aug 22 13:40:39 notebook-ros podman[460901]: @ - - [22/Aug/2023:13:40:39 +0200] "POST /v4.6.0/libpod/containers/create HTTP/1.1" 500 112 "" "curl/7.81.0"
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="IdleTracker:idle 1m+0h/1t connection(s)" X-Reference-Id=0xc0005deb00
Aug 22 13:40:39 notebook-ros podman[460901]: time="2023-08-22T13:40:39+02:00" level=debug msg="IdleTracker:closed 1m+0h/1t connection(s)" X-Reference-Id=0xc0005deb00
Aug 22 13:40:44 notebook-ros podman[460901]: time="2023-08-22T13:40:44+02:00" level=debug msg="API service(s) shutting down, idle for 5s"
Aug 22 13:40:44 notebook-ros podman[460901]: time="2023-08-22T13:40:44+02:00" level=debug msg="API service shutdown, 0/1 connection(s)"
Aug 22 13:40:44 notebook-ros podman[460901]: time="2023-08-22T13:40:44+02:00" level=debug msg="API service forced shutdown, ignoring timeout Duration"
Aug 22 13:40:44 notebook-ros podman[460901]: time="2023-08-22T13:40:44+02:00" level=debug msg="Called service.PersistentPostRunE(/usr/bin/podman --log-level=trace system service)"
Aug 22 13:40:44 notebook-ros podman[460901]: time="2023-08-22T13:40:44+02:00" level=debug msg="Shutting down engines"
```

**Comment by ewie** [comment]
> As I am having the same problem, I tried nearly the same but I do get a HTTP 500 response from the API service:
> 
> ```
> ─$ curl -v -H 'Content-Type: application/json' --data '{"image": "docker.io/library/elasticsearch:7.17.10"}' --unix-socket /var/run/user/1000/podman/podman.sock http://localhost/v4.6.0/libpod/containers/create
> *   Trying /var/run/user/1000/podman/podman.sock:0...
> * Connected to localhost (/run/user/1000/podman/podman.sock) port 80 (#0)
> > POST /v4.6.0/libpod/containers/create HTTP/1.1
> > Host: localhost
> > User-Agent: curl/7.81.0
> > Accept: */*
> > Content-Type: application/json
> > Content-Length: 52
> > 
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 500 Internal Server Error
> < Api-Version: 1.41
> < Content-Type: application/json
> < Libpod-Api-Version: 4.6.1
> < Server: Libpod/4.6.1 (linux)
> < X-Reference-Id: 0xc0005deb00
> < Date: Tue, 22 Aug 2023 11:40:39 GMT
> < Content-Length: 112
> < 
> {"cause":"image not known","message":"docker.io/library/elasticsearch:7.17.10: image not known","response":500}
> * Connection #0 to host localhost left intact
> ```

Thanks @rsommer!

I get a 404 response via http://localhost/containers/create. Via http://localhost/v4.6.0/libpod/containers/create (as in your sample) I also get the same 500 response.

**Comment by rsommer** [comment]
This is what `podman-py` sends to the socket - it is using the version prefixed endpoints:
```
POST /v4.6.0/libpod/containers/create HTTP/1.1
Host: %2frun%2fuser%2f1000%2fpodman%2fpodman.sock
User-Agent: PodmanPy/4.6.0 (API v4.6.0; Compatible v1.40)
Accept-Encoding: gzip, deflate, br, zstd
Accept: */*
Connection: keep-alive
content-type: application/json
Content-Length: 52

{"image": "docker.io/library/elasticsearch:7.17.10"}
```

**Comment by umohnani8** [comment]
This has been fixed in podman upstream/main, podman-py against the latest podman should return the expected 404 code for a missing image now.
