### ISSUE TITLE
List tags parameter on images search method

### ISSUE THREAD

**Issue by madhuravius** [containers/podman-py#264]
I believe `listTags` (`--list-tags` equivalent on cli / [api](https://github.com/containers/podman/blob/19152fa349199e88212aa9607c27139730d1710b/pkg/api/handlers/compat/images_search.go#L26)) is a flag that can be enabled on podman's api for the search behavior: https://docs.podman.io/en/latest/markdown/podman-search.1.html#list-tags

It would be nice to have this flag enabled so we can search for these tags in our results. I have a [simple proof here of function below](https://github.com/madhuravius/podman-py/pull/1). 

```py
>>> from podman import PodmanClient
>>> import pprint as pp
>>> uri = "unix:///run/user/1000/podman/podman.sock"
>>> client = PodmanClient(base_url=uri)
>>> pp.pprint(client.images.search(term="docker.io/nginx", list_tags=True)[0:5])
[{'Automated': '',
  'Description': '',
  'Index': 'docker.io',
  'Name': 'docker.io/library/nginx',
  'Official': '',
  'Stars': 0,
  'Tag': '1'},
 {'Automated': '',
  'Description': '',
  'Index': 'docker.io',
  'Name': 'docker.io/library/nginx',
  'Official': '',
  'Stars': 0,
  'Tag': '1-alpine'},
...
```

I did not see a comparable issue opened for this.

**Comment by inknos** [comment]
Closing, looks like it's fixed on the linked pr. Don't hesitate to reopen if more attention is needed :)
