### ISSUE TITLE
Question: How to map a volume:O to the mount syntax

### ISSUE THREAD

**Issue by mkanoor** [containers/podman-py#269]
How do we take a volume definition like /etc/pki/ca-trust:/etc/pki/ca-trust:O and use it with a mount object.
How is the O option specified in a mount object like specified here
https://github.com/containers/podman-py/blob/1276e39d488ede3c83e994fddc9f8aa89aa5078f/podman/domain/containers_create.py#L103

**Comment by rhatdan** [comment]
Looks like we might need to enhance the bindings for this.

**Comment by mkanoor** [comment]
@rhatdan Is there a way to do this with volumes, the volumes notes say that it can be a path or a name
https://github.com/containers/podman-py/blob/454f60fcd422731bb1587696a20ab895f47f6749/podman/domain/containers_create.py#L238

```
kwargs['volumes'] = {'/etc/pki/ca-trust': { 'bind': '/etc/pki/ca-trust', 'extended_mode': ['O'] }}
```


But when we set it to a path, libpod service complains about path not being well conforming name.
```
INFO[0038] Request Failed(Internal Server Error): error creating named volume "/etc/pki/ca-trust": running volume create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument 

```

On another note is doing an overlay mount of the certs into the container a security issue.
podman run -v  /etc/pki/ca-trust:/etc/pki/ca-trust:O ....

I am trying to get the python podman library to support the above syntax when running a container. Is there another way to achieve this.

**Comment by sibidass** [comment]
I am also facing the same problem. as per the podman-py doc, I can set either hostPath or name as the key. But when I set hostPath as the key, I am getting similar error:

`podman.errors.exceptions.APIError: 500 Server Error: Internal Server Error (creating named volume "/tmp/hostpath": running volume create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument)`

**Comment by sibidass** [comment]
eventually I used the mount option to mount hostpath. It is working fine.

**Comment by umohnani8** [comment]
We are using https://github.com/containers/podman-py/issues/151 to track the volume issue. Closing this as it is a dupe and seems like a workaround with the mount option was possible.
