### ISSUE TITLE
PEP8 style guide

### ISSUE THREAD

**Issue by danvergara** [containers/podman-py#28]
As a python developer and a big fan of podman, I might find this package useful in order to automate some container processes. But now, I see there's a lack of features and I think this is a perfect moment to improve code quality. [PEP8](https://www.python.org/dev/peps/pep-0008/) is the official style guide for python and this library could follow those principles in a more strictly way.

i. e.

Before PEP8
```python
def __init__(self, url, base="/v1.24/libpod", *args,
    **kwargs):  # pylint: disable-msg=W1113
```

After PEP8
```python
def __init__(
    self, url, base="/v1.24/libpod", *args, **kwargs
):  # pylint: disable-msg=W1113
```

**Comment by jwhonce** [comment]
@danvergara I agree on setting a style. I've been using the `black` formatter to enforce style. It's a slight delta from PEP8 but not in a bad way.  For example, 100 line length vs. 80 (we're no longer using vt100's or IBM cards); enforcing double quotes over single quotes, unless embedded.  The best part of `black` is that it does not change the AST of your code, unlike tools like `isort` so it's safe to include in automation tool chains.

/cc @mwhahaha @baude 

If we're in agreement on this tool, I'll update the CONTRIBUTING.md to reflect this choice. I will also check with our automation guys to see if we could run `black` on each PR before running the tests.

/cc @cevich @TomSweeneyRedHat

**Comment by mwhahaha** [comment]
We can also add black to pre-commit or via tox. It'd also be good to ensure we have consistent black configs.  Over in OpenStack, black hasn't really picked up any traction so I'm used to the more strict pep8 rules but I think it'd be a good idea to automate it via black.

**Comment by cevich** [comment]
> see if we could run black on each PR before running the tests.

I'm assuming you mean on ***this*** repo?  There is a a very basic `.cirrus.yml` here already.  Maybe stick the [call to the black check above this line?](https://github.com/containers/podman-py/blob/master/.cirrus.yml#L42)
