### ISSUE TITLE
podman-py is incompatible with urllib3

### ISSUE THREAD

**Issue by dcermak** [containers/podman-py#281]
While updating podman-py in openSUSE, I realized that it is incompatible with urllib3 as `NetworkTestCase.test_remove` fails with:
```
[   14s] E                   urllib3.exceptions.IncompleteRead: IncompleteRead(31 bytes read, -31 more expected)
```

Are there any plans to support urllib3 version 2.x eventually?

**Comment by umohnani8** [comment]
Hey @cevich, you did some work on updating urlib3 to 2.x and then reverting it, what was going on and any idea if we can support urlib3 2.x now?
