### ISSUE TITLE
network.create() prints json response to stderr

### ISSUE THREAD

**Issue by chnrxn** [containers/podman-py#309]
https://github.com/containers/podman-py/blob/main/podman/domain/networks_manager.py#L76

The create method is writing the JSON response to stderr. It is unexpected behaviour from a library method.

```
        response = self.client.post(
            "/networks/create",
            data=http_utils.prepare_body(data),
            headers={"Content-Type": "application/json"},
        )
        response.raise_for_status()
        sys.stderr.write(str(response.json()))
        return self.prepare_model(attrs=response.json())
```

**Comment by rhatdan** [comment]
That would seem to be a debug issue?

**Comment by jwhonce** [comment]
@rhatdan Yeah, it appears to be a debugging turd that got left in the code.

@chnrxn Thank you for bringing that to our attention.

**Comment by jwhonce** [comment]
Fixed by https://github.com/containers/podman-py/pull/311
