### ISSUE TITLE
demux doesn't work in exec_run => no way to separate stdout and stderr

### ISSUE THREAD

**Issue by maxi0604** [containers/podman-py#322]
Hello,

It seems like `demux` in `Container.exec_run` doesn't work, and that there is currently no way to separate stdout and stderr when using `exec` through this library. Quickly looking at the code, it seems to me like the `demux` parameter is only referenced in the doc comment, but not used in the code: https://github.com/containers/podman-py/blob/004ebda439975fdf81d87e84ae1387cf1aa0d3fe/podman/domain/containers.py#L142C1-L142C14

Thanks for considering this issue

**Comment by inknos** [comment]
ack. not just that, `stream` parameter is also unused there. I am taking a look

**Comment by omkarkhatavkar** [comment]
@inknos Do you have any further update on fixing this issue ?

**Comment by JacobCallahan** [comment]
@maxi0604 If you want to take the implementation I did for demuxing, you can see it here: https://github.com/SatelliteQE/broker/blob/master/broker/binds/containers.py#L8-L48

**Comment by inknos** [comment]
> Do you have any further update on fixing this issue ?

I am sorry I got distracted by other duties and forgot after PTO. will move it on the higher priority now.
