### ISSUE TITLE
Equivalent of docker-py 'client.api.inspect_distribution()'

### ISSUE THREAD

**Issue by mkst** [containers/podman-py#325]
Firstly, thank you to everyone that has worked on this project. I find myself in a situation where i need to pull docker images from within a docker container without any privileges.

I'm trying to compare local images against remote registry. I have working code for the docker-py bindings, but I'm getting different hashes back from the podman-py bindings.

I would like to call this endpoint `http+docker://localhost/v1.43/distribution/ghcr.io/mkst/compilers/nds_arm9/mwcc_30_114:latest/json`, which I can do via docker-py, but I cannot find an equivalent in podman-py.
```
>>> docker_image = "ghcr.io/mkst/compilers/nds_arm9/mwcc_30_114:latest"
>>> docker_client.api.inspect_distribution(docker_image)
{
  'Descriptor': {
    'mediaType': 'application/vnd.oci.image.index.v1+json', 
    'digest': 'sha256:11d59de1ea458a6acd6ae729d955494f4dc467a726a98a53602daa238557c3f1', // this is the "parent" id
    'size': 855
}, 
  'Platforms': [{'architecture': 'amd64', 'os': 'linux'}, {'architecture': 'unknown', 'os': 'unknown'}]
}
```
Alternatively, what do I need to feed client.api.get() in order to get the parent `11d59...` hash:

![image](https://github.com/containers/podman-py/assets/22226349/5a45a060-f180-4db3-bb06-30d264d8bd94)

I can get it for the *local* image (although i guess I have to just pick the first RepoDigest? is that deterministic?):
```
>>> podman_client.images.get(docker_image).attrs
{
  'Id': 'bb998df69a4aaf40ec6790bc563a162cf9b63934f4e551a3123914c32389344a', 
  'Digest': 'sha256:11d59de1ea458a6acd6ae729d955494f4dc467a726a98a53602daa238557c3f1', 
  'RepoTags': ['ghcr.io/mkst/compilers/nds_arm9/mwcc_30_114:latest'], 
  'RepoDigests': ['ghcr.io/mkst/compilers/nds_arm9/mwcc_30_114@sha256:11d59de1ea458a6acd6ae729d955494f4dc467a726a98a53602daa238557c3f1', 'ghcr.io/mkst/compilers/nds_arm9/mwcc_30_114@sha256:b4185bd52d9cc53deecc9ee24c44a036b3613cf94edc592bfb2b84be87fd156f'], 
  'Parent': '', 
  'Comment': 'buildkit.dockerfile.v0', 
  'Created': '2023-09-14T10:36:34.421474411Z', 
  'Config': {'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'], 'WorkingDir': '/'}, 'Version': '', 'Author': '', 'Architecture': 'amd64', 'Os': 'linux', 'Size': 4736225, 'VirtualSize': 4736225, 'GraphDriver': {'Name': 'vfs', 'Data': None}, 'RootFS': {'Type': 'layers', 'Layers': ['sha256:93b4c624abaa80b865bf220210c08d445c2c6381f1bb27ca7fa114b0b4257b56']}, 'Labels': None, 'Annotations': {}, 'ManifestType': 'application/vnd.oci.image.manifest.v1+json', 'User': '', 'History': [{'created': '2023-09-14T10:36:34.421474411Z', 'created_by': 'COPY /compilers /compilers # buildkit', 'comment': 'buildkit.dockerfile.v0'}], 'NamesHistory': ['ghcr.io/mkst/compilers/nds_arm9/mwcc_30_114:latest']}
```
but I can't seem to get it remotely:
```
>>> podman_client.manifests.get(docker_image).attrs
{
  'schemaVersion': 2, 
  'mediaType': 'application/vnd.docker.distribution.manifest.list.v2+json', 
  'manifests': [
  {
    'mediaType': 'application/vnd.oci.image.manifest.v1+json', 
    'size': 480, 
    'digest': 'sha256:b4185bd52d9cc53deecc9ee24c44a036b3613cf94edc592bfb2b84be87fd156f', 
    'platform': {'architecture': 'amd64', 'os': 'linux'}
  }, 
  {
    'mediaType': 'application/vnd.oci.image.manifest.v1+json', 
    'size': 566, 
    'digest': 'sha256:b6cabbe8342853fbe9c0a367bad2632356840b251337c4c51735b03a3c4041e0', 
    'platform': {'architecture': 'unknown', 'os': 'unknown'}
  }
  ], 
    'names': 'ghcr.io/mkst/compilers/nds_arm9/mwcc_30_114:latest'
}
```
Is there a different method I can use?

**Edit**:

Following on from this, I'm trying to extract the value out of ghcr.io's V2 API. but it seems futile. Their API does not seem to support the 'fat' manifest (`application/vnd.docker.distribution.manifest.v2+json`), only the `oci` ones (`application/vnd.oci.image.manifest.v1+json`). Which means I am really confused as to how Docker is managing to pull that digest (even podman pulls out the 'fat' manifest *list*).

```json
$ export TOKEN=$(curl --silent https://ghcr.io/token\?scope\="repository:mkst/compilers/nds_arm9/mwcc_30_114:pull" | jq --raw-output .token)
$ curl --silent  -H "Accept: application/vnd.docker.distribution.manifest.v2+json"   -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json"   -H "Accept: application/vnd.oci.image.index.v1+json"   -H "Accept: application/vnd.oci.image.manifest.v1+json"   -H "Authorization: Bearer ${TOKEN}"   https://ghcr.io/v2/mkst/compilers/nds_arm9/mwcc_30_114/manifests/latest | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:b4185bd52d9cc53deecc9ee24c44a036b3613cf94edc592bfb2b84be87fd156f",
      "size": 480,
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:b6cabbe8342853fbe9c0a367bad2632356840b251337c4c51735b03a3c4041e0",
      "size": 566,
      "annotations": {
        "vnd.docker.reference.digest": "sha256:b4185bd52d9cc53deecc9ee24c44a036b3613cf94edc592bfb2b84be87fd156f",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    }
  ]
}
```

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
> I'm trying to compare local images against remote registry.

I… suspect that you are going to end up defining in much more detail what a match means, with image deduplication and differently-compressed variants of “the same” image and the like.

Let’s go with matching the top-level digest, for now, that’s a reasonable semantic in many situations.

---

> I would like to call this endpoint `http+docker://localhost/v1.43/distribution/ghcr.io/mkst/compilers/nds_arm9/mwcc_30_114:latest/json`, which I can do via docker-py, but I cannot find an equivalent in podman-py.

(The client can contain the registry directly, as you have found, so I can’t see the value of a server intermediating. But it’s up to Podman maintainers, not me, whether to implement that endpoint. At this point I’m just looking to clarify the situation.)

---

> Alternatively, what do I need to feed client.api.get() in order to get the parent `11d59...` hash:

There is no “the” hash. The local image can be deduplicated from pulling from several different repositories (or from pulling several representations from the same repository, in the worst case). You’ll need to account for that when matching, depending on your use case.

> I can get it for the _local_ image (although i guess I have to just pick the first RepoDigest? is that deterministic?):
> ```
> >>> podman_client.images.get(docker_image).attrs
> ```

No, it’s not always the first one. It should be listed as one of the values, the order is unspecified and subject to change.

When pulling by tag, or by the top-level digest, the top-level digest is going to be included. As a corner case, `podman pull …@sha256:per-arch-digest` can create a record where the top-level digest is not listed in `RepoDigests`. It’s not possible to find the top-level multi-arch digest from a per-arch digest value.

---

> but I can't seem to get it remotely:
> 
> ```
> >>> podman_client.manifests.get(docker_image).attrs
> ```

Note `images` vs. `manifests`. (The `manifest` output is strange — why is it mixing `vnd.docker` and `vnd.oci`? I don’t fully understand the `manifests` feature … either way it’s, AFAIK, irrelevant to the task at hand.)

---
 
> Following on from this, I'm trying to extract the value out of ghcr.io's V2 API. but it seems futile. Their API does not seem to support the 'fat' manifest (`application/vnd.docker.distribution.manifest.v2+json`), only the `oci` ones (`application/vnd.oci.image.manifest.v1+json`). Which means I am really confused as to how Docker is managing to pull that digest (even podman pulls out the 'fat' manifest _list_).

I don’t really understand what you are saying here… my guess is that this is some confusion. `oci.image.index` is the top-level object, `oci.image.manifest` is a component.

> ```json
> $ export TOKEN=$(curl --silent https://ghcr.io/token\?scope\="repository:mkst/compilers/nds_arm9/mwcc_30_114:pull" | jq --raw-output .token)
> $ curl --silent  -H "Accept: application/vnd.docker.distribution.manifest.v2+json"   -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json"   -H "Accept: application/vnd.oci.image.index.v1+json"   -H "Accept: application/vnd.oci.image.manifest.v1+json"   -H "Authorization: Bearer ${TOKEN}"   https://ghcr.io/v2/mkst/compilers/nds_arm9/mwcc_30_114/manifests/latest | jq
> ```

Almost there — instead, `curl … | bin/skopeo manifest-digest /dev/stdin`; or, if you can guarantee the images don’t use the schema1 format, `curl … | {sha256sum,shasum -a 256}`.

(Note that `latest` has moved in the meantime, so the original examples are no longer perfectly reproducible.)

**Comment by mkst** [comment]
Thank you for your reply, it's got me to a place where started looking into skopeo and then stumbled acros [this](https://opendev.org/openstack/tripleo-common/commit/28a5ba0a01383f69b3a8880286830d4c00901fc4) PR.

The short answer is: **The hash I want is returned in the `docker-content-digest` header of the response, not in the message body.**
```
< HTTP/2 200 
< content-length: 855
< content-type: application/vnd.oci.image.index.v1+json
< docker-content-digest: sha256:cde0692bc900f5dce750fdc5e2374d5f6452a8c723f3e712088a1c45bbb6c642
< docker-distribution-api-version: registry/2.0
< etag: "sha256:cde0692bc900f5dce750fdc5e2374d5f6452a8c723f3e712088a1c45bbb6c642"
< date: Mon, 18 Sep 2023 18:05:55 GMT
< x-github-request-id: A378:9C41:2E95104:2FE050F:65089183
< 
```

This means I can replace my registry calls with a `requests.get()` and move on - I'm in control of the images that are pushed to the registry (apologies that the example in my original post are already out of date!), and for now there will only be 1 remote registry.

Thanks again, I will close this issue :+1:
