### ISSUE TITLE
anonymous volumes not removed after container removal

### ISSUE THREAD

**Issue by aparcar** [containers/podman-py#328]
I'm creating and removing containers in a fast paste and the anonymous volumes quickly fill up the drives. I'm removing the containers with `container.remove(v=True)`, however a volume containing modified files stays.

Currently I'm running library version 4.5.0 but I suspect it's the same issue with 4.6.0 since I couldn't find anything in the change notes. 

If this is likely an upstream problem I'll report the issue there.

**Comment by jwhonce** [comment]
@aparcar Yes, that would seem to be more of a podman issue than podman-py, as you can see below the python code simply makes a RESTful call.

[response = self.client.delete(f"/containers/{container_id}", params=params)
](https://github.com/containers/podman-py/blob/6edcd2d566ed0d87b98a2be8a869e494dbc21a93/podman/domain/containers_manager.py#L146)
