### ISSUE TITLE
Q: can podman-py be used as a drop in replacement for the docker python module?

### ISSUE THREAD

**Issue by TTimo** [containers/podman-py#336]
Hello,

I am looking at switching or adding support to a set of scripts that use the docker python api - does podman have a compatible API, at least for the most common high level functionality so that I could use this module as a drop in replacement?

**Comment by jwhonce** [comment]
> Hello,
> 
> I am looking at switching or adding support to a set of scripts that use the docker python api - does podman have a compatible API, at least for the most common high level functionality so that I could use this module as a drop in replacement?

At the source level, yes. You  do not need to rewrite your docker-py code assuming your server is podman. If you want to point podman-py to a docker backend you need to add the `compatible` flag to your calls. This is bench checked, I do not  believe there are any tests to ensure everything works as expected.

The podman server has compatibility endpoints to support the docker API and an specialized set of endpoints for podman. podman-py defaults to talking to a podman server.

**Comment by TTimo** [comment]
Thank you. I did not get to try this yet, but this was valuable feedback.
