### ISSUE TITLE
support for python 3.12+ ?

### ISSUE THREAD

**Issue by lsm5** [containers/podman-py#397]
Filing this to get everyone's eyes just in case.

Looks like there was some recent python update on rawhide that broke a few python packages.

I don't know if it's a rawhide problem and if things will magically be resolved on the fedora side itself OR if we need any changes in podman-py but I'm currently unable to install python-podman from the podman-next copr on my local rawhide environment. 

Also, setup.cfg upstream only mentions up to 3.11.

```
$ sudo dnf install python-podman
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
Problem: cannot install the best candidate for the job
  - nothing provides python3.12dist(urllib3) needed by python3-podman-102:5.0.0-1.20240603145722613969.main.21.g17e4846.fc41.noarch from copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next
  - nothing provides python(abi) = 3.12 needed by python3-podman-102:5.0.0-1.20240603145722613969.main.21.g17e4846.fc41.noarch from copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next
  - nothing provides python3.12dist(pyxdg) >= 0.26 needed by python3-podman-102:5.0.0-1.20240603145722613969.main.21.g17e4846.fc41.noarch from copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next
  - nothing provides python3.12dist(requests) >= 2.24 needed by python3-podman-102:5.0.0-1.20240603145722613969.main.21.g17e4846.fc41.noarch from copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next
You can try to add to command line:
  --no-best to not limit the transaction to the best candidates
  --skip-broken to skip uninstallable packages

```

**Comment by lsm5** [comment]
@inknos PTAL

**Comment by jwhonce** [comment]
Adding `py312` to the envlist in the `tox.ini` file would be the first step to having that environment tested.

Most of the dependencies are allowed to float to the current defaults on each platform. @inknos knows about the issue with `pyxdg` not being supported and has solutions. The `urllib3` and `requests` libraries are worrisome.
