### ISSUE TITLE
https://github.com/containers/podman-py/blob/release-4.9/docs/source/index.rst has the wrong podman client call

### ISSUE THREAD

**Issue by wblakeh** [containers/podman-py#404]
- The example on the index.rst page shows calling the podman client with `with podman.Client() as client:` which results in the following error when running the example script on index.rst

~~~
Traceback (most recent call last):
  File "/home/python/./podman-test2.py", line 7, in <module>
    with podman.Client(base_url=uri) as client:
AttributeError: module 'podman' has no attribute 'Client'
~~~

- The main landing page for podman-py shows calling with this example `with PodmanClient(base_url=uri) as client:` which successfully runs the example script on the homepage.

**Comment by inknos** [comment]
I believe this is fixed by this PR

https://github.com/containers/podman-py/pull/405
