### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by aparcar** [containers/podman-py#411]
Hi, with the recent change of adding demuxing to `exec_run`, it'd be very nice to have a new release.

https://github.com/containers/podman-py/commit/05d1e7cb89b45fb80a71320de6f011e29022b5a7

**Comment by rhatdan** [comment]
Should be a podman-py 5.2 release soon.

@umohnani8 @jwhonce @TomSweeneyRedHat WDYT?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan sounds like an excellent plan.  @mheon want to spin up a RUN card to make sure we don't miss it?  Or is it already there.

**Comment by mheon** [comment]
I believe @inknos was planning one for around the time Podman 5.2 came out?

**Comment by inknos** [comment]
yup, I'll keep it in sync with Podman 5.2
