### ISSUE TITLE
Arguments missing for podman load and podman login?

### ISSUE THREAD

**Issue by CVC0316** [containers/podman-py#419]
Hi all!

I'm currently using podman-py to automatically load, tag and push images to a local registry. 

Now I've run into two problems.

The first one is that the images.load method takes no arguments like a path - at least as far as I can see. If I need to load an image from a tgz archive I'd expect the load method to accept a path instead of binary only. I'm not sure how to load any images with this implementation as I'd basically have to pipe the tgz into the method somehow? With podman I have the option "-i" but I don't see anything like that in the methods currently implemented. 

Furthermore I wanted to ask if there's an option to add a flag like --tls-verify=false for the login method. That's a smaller thing that's rather easy to work around of course. Still it might be nice to have if you're working with a local registry. 

Best regards and thanks in advance!

**Comment by inknos** [comment]
@CVC0316 , thanks for the report. Currently, the podman-py's api is slightly off sync with podman, and some opts/pars might be missing. I am planning to bring it back to sync, but it takes time.

Would you like to open a PR to fix it or to take care of part of it? I can help if needed.

**Comment by inknos** [comment]
Fixed https://github.com/containers/podman-py/pull/434

Please reopen if some features are missing
