### ISSUE TITLE
Deploy new PyPi release

### ISSUE THREAD

**Issue by milanbalazs** [containers/podman-py#424]
I would be nice to deploy a new PyPi  release (5.2.0).

The latest podman-py release is 5.2.0 but the latest PyPi release is 5.0.0. There are many changes are included in the new release, which would be nice to use via PyPi.

**PyPi:**

- https://pypi.org/project/podman/

**Comment by inknos** [comment]
Apologies, some delays with integration tests, but 5.2.0 is now released https://pypi.org/project/podman/5.2.0/

**Comment by milanbalazs** [comment]
@inknos No Problem! Thanks!
