### ISSUE TITLE
Tests are failing with timeout error

### ISSUE THREAD

**Issue by inknos** [containers/podman-py#425]
Reproduces in GH and locally

1. pull upstream
2. `make tests`

tests get stuck at `podman/tests/integration/test_containers.py::ContainersIntegrationTest::test_container_crud`

See https://github.com/containers/podman-py/pull/420/checks?check_run_id=28860969899

**Comment by inknos** [comment]
After bisecting podman, this is the first commit where podman-py tests hang https://github.com/containers/podman/commit/8a943311db5b686af231ddc026b7a0a072eb25d2

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by inknos** [comment]
I have a reproducer which is making me scratch my head

```python
from podman import PodmanClient
import subprocess

uri = "unix:///run/user/1000/podman/podman.sock"

client = PodmanClient(base_uri=uri)

c = client.containers.create('nginx:latest', name="test", detach=True)

print(client.containers.get(c.id)) # this line hangs
```

now, if you do

```python
for i in range(5):
    print(i)
    print(client.containers.get(c.id))
```

only the last get call in the loop hangs

**Comment by Luap99** [comment]
I am not familiar with the python code here but if you do not call the wait endpoint then the linked commit should not change anything as the code is only used in there unless I am overlooking something.

Looking at your reproducer it doesn't even start the container so there is no reason to call wait either, and I cannot reproduce with your small python example either unless I did something wrong? I just copied your reproducer to a file in this repo and then just run it.

**Comment by inknos** [comment]
apologies I deleted the comment with the reproducer already because it was incorrect. 

> if you do not call the wait endpoint then the linked commit should not change anything as the code is only used in there unless I am overlooking something

your comment shed some light, now I actually have something that can reproduce it

```python
from podman import PodmanClient
import subprocess

uri = "unix:///run/user/100/podman/podman.sock"
client = PodmanClient(base_uri=uri)

c = client.containers.create('nginx:latest', name="test", detach=True)
c.start()
```
works

```python
c = client.containers.run('nginx:latest', name="test", detach=True)
```
hangs

I think I know where to look now

**Comment by Luap99** [comment]
Yes that makes more sense, I was able to reproduce with the test case once I figure out the dependencies.

I see `container.wait(condition=["running", "exited"])` being called there but I really really do not understand the purpose of this call. After start is done it is safe to assume the container is running (or well it could have any other state as well as in the meantime the process could have exited or any other podman command might have changed the state) so this call doesn't seem to do anything useful. In fact the caller asked for detach and we still wait?

**Comment by inknos** [comment]
not sure about this line. I found new issues related to getting the right status. it seems like the call will indeed wait forever since the status looks to be `created` every time.

```
>>> c = client.containers.create('nginx:latest', detach=True)
>>> c.status
'created'
>>> c.start()
>>> c.status
'created'
```

**Comment by Luap99** [comment]
In theory exited cannot happen in your reproducer however the wait condition should trigger on running as well so something must be wrong with that. The logic should return if any state was hit however it currently blocks forever.

I see what is causing this on the podman side and will look into a fix on the podman side tomorrow.

However I would recommend you drop the wait call there, it is not doing anything useful AFAICS.

> the status looks to be created every time.

You will have to call reload() because the python code of course doesn't really understand state changes on the podman side, the API has no real way to update the state fields on its own so you must do an explicit reload which in turn does an inspect on the server and then just updates the attrs filed with that. c.state itself just returns self.attrs["State"]["Status"]

**Comment by jwhonce** [comment]
@Luap99 The wait call is blocking on the container on the server to be in the correct state. So a reload() is not required. These semantics are to be compatible.

**Comment by Luap99** [comment]
> @Luap99 The wait call is blocking on the container on the server to be in the correct state. 

Well if you call start the container is always running on the server, calling wait for running afterwards is just pointless.

**Comment by inknos** [comment]
Should the `run` function then call `wait` only in certain cases? I can see that for a detached container does not make much sense, but maybe it does for a container which is not detached. in my opinion, the behaviors should be consistent, so I would cut it tbh.

I think `wait` makes a lot of sense for scripting purposes, but not within the run function context. after all isn't `run` just `create`+`start`?

**Comment by Luap99** [comment]
In the non detached case it already calls wait() (without args so it waits for exit) later which is correct, `exit_status = container.wait()`. I think run should largely follow what podman run is doing.

**Comment by jwhonce** [comment]
I plead very bad git history, sorry guys. I added that condition without explanation. I want to say the idea was to have the reload() be correct and there was a race condition. I infer this because the wait() was added with integration tests comment.

Over the last three years the server semantics may have changed enough that the race condition no longer exists.

**Comment by inknos** [comment]
@jwhonce, we recently had an update in our docs where `reload()` was written explicitly for getting the status of a container. I believe wait can be removed and maybe reload too.

Actually, to improve getting the correct status, what about trying to reload directly within [in the status property](https://github.com/containers/podman-py/blob/main/podman/domain/containers.py#L51-L56)?

**Comment by Luap99** [comment]
> Actually, to improve getting the correct status, what about trying to reload directly within [in the status property](https://github.com/containers/podman-py/blob/main/podman/domain/containers.py#L51-L56)?

Note that an inspect call is rather expensive. I am not sure how the code is used in general but if one does if c.status == "foo" || c.status == "bar" than having the status change in between might be a bad thing?
