### ISSUE TITLE
container.logs doc string states stderr defaults to True when infact it defaults to False

### ISSUE THREAD

**Issue by MattBelle** [containers/podman-py#451]
The docstring for container.logs states that the default value of the stderr keyword arg is True, when in fact if you look at the function code it defaults to None which is treated as False

**Comment by inknos** [comment]
@MattBelle Thanks, would you like to open a PR to fix it? I can help with a review

**Comment by MattBelle** [comment]
Done: https://github.com/containers/podman-py/pull/452
