### ISSUE TITLE
Error handling in api.request

### ISSUE THREAD

**Issue by ngaller** [containers/podman-py#47]
Hello, and thank you for making this package!

I noticed that in the `api.request` method, the error message returned by the server is not captured.  For example we might get:

    podman.errors.InternalServerError: Request POST:/v2.0.0/libpod/containers/create failed: Server got itself in trouble

Instead of:

    Decode(): json: cannot unmarshal string into Go struct field SpecGenerator.cni_networks of type []string

Is that on your roadmap, or would you be open to a PR adding that handling?

**Comment by mwhahaha** [comment]
Was that message part of the actual response in some form? I believe this gets thrown because it's a 500

**Comment by ngaller** [comment]
- The first message is the message from the exception
- The second message comes from the actual response and you can still access it with `e.response.read()`, so I use this code for now to wrap the API calls:

```
            try:
                response = api.post("/containers/create", json.dumps(params))
            except http.client.HTTPException as e:
                error_content = e.response.read()
                if error_content:
                    error_content_parsed = json.loads(error_content)
                    raise Exception(error_content_parsed["message"])
                raise
```

**Comment by mwhahaha** [comment]
Seems reasonable. Feel free to submit a pull request
