### ISSUE TITLE
containers/create needs parameter

### ISSUE THREAD

**Issue by krevsbech** [containers/podman-py#64]
According to the swagger documentation and the implementation of Podman 2.0 REST API the container name must a query parameter, and container data the parameters. 
Currently only container data is send, not the name which results in HTTP error 500.

I've tested with CURL: 
`curl --unix-socket <> -X POST  "http://d/v2.0.0/containers/create?name=<name>" -H "Content-Type: application/json" -d "{\"Image\":\"alpine\"}"` which works.
I will be happy to fix it, but I am having a hard time to see how that should be done using the current http lib, and the POST abstractions done.

**Comment by jwhonce** [comment]
@krevsbech `PodmanClient()` has been introduced and resolves this issue and a number of others. APIConnection() will be deprecated and deleted in the future. `PodmanClient()` more closely aligns with docker-py to ease the transition to podman.

**Comment by jwhonce** [comment]
See https://pypi.org/project/podman-py

```
with podman.PodmanClient() as client:
    image = client.images.pull("quay.io/libpod/alpine", tag="latest")
    container = client.containers.create(image, command=["echo", random_string], name="krevsbech_ctnr")
    ....
```
