### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-py#90]

**Comment by jwhonce** [comment]
To all, you will need to make these changes to your environments.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

/cc @lsm5 @mwhahaha @baude

**Comment by lsm5** [comment]
no worries on the packaging side.

**Comment by rhatdan** [comment]
SGTM, already ran your script, do you want me to reset the repo, or can you do this?

**Comment by jwhonce** [comment]
I made the change and created PR #93 to update documentation.
